### ISSUE TITLE
ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by moonlightly** [PAC-ROM/android_vendor_pac#158]
when packing zip,it tells that:

unzipping target target-files...
  running:  unzip -o -q /home/moonlight/pacman/out/target/product/n7100/obj/PACKAGING/target_files_intermediates/pac_n7100-target_files-eng.moonlight.zip -d /tmp/targetfiles-m1Y6h0
Traceback (most recent call last):
  File "vendor/pac/overlay/build/tools/releasetools/ota_from_target_files", line 936, in <module>
    main(sys.argv[1:])
  File "vendor/pac/overlay/build/tools/releasetools/ota_from_target_files", line 879, in main
    OPTIONS.info_dict = common.LoadInfoDict(input_zip)
  File "/home/moonlight/pacman/vendor/pac/overlay/build/tools/releasetools/common.py", line 156, in LoadInfoDict
    d["build.prop"] = LoadBuildProp(zip)
  File "/home/moonlight/pacman/vendor/pac/overlay/build/tools/releasetools/common.py", line 170, in LoadBuildProp
    name, value = line.split("=", 1)
ValueError: need more than 1 value to unpack
make: **\* [/home/moonlight/pacman/out/target/product/n7100/pac_n7100-ota-eng.moonlight.zip] error1

**Comment by wangyou** [comment]
I met a the same problems with you! Can be tell me how to solve it? ? ? Thank you very much！！！
